export const AUTH_SIGN_UP = "AUTH_SIGN_UP";
export const AUTH_SIGN_UP_ASYNC = "AUTH_SIGN_UP_ASYNC";

export const AUTH_ERROR = "AUTH_ERROR";

export const AUTH_SIGN_OUT_ASYNC = "AUTH_SIGN_OUT_ASYNC";
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";

export const AUTH_SIGN_IN = "AUTH_SIGN_IN";
export const AUTH_SIGN_IN_ASYNC = "AUTH_SIGN_IN_ASYNC";

export const GET_SECRET = "GET_SECRET";
export const GET_SECRET_ASYNC = "GET_SECRET_ASYNC";
export const DATA_LOADING = "DATA_LOADING";
export const DELETE_POST = "DELETE_POST";
export const SEND_ARTICLE = "SEND_ARTICLE";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const SEND_COMMENT = "SEND_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS";
export const EDIT_ARTICLE = "EDIT_ARTICLE";
export const DATA_LOADED = "DATA_LOADED";
export const COMMENTS_LOADED = "COMMENTS_LOADED";
